# Jasmine J.

## 11-06-2023

## Week 5 - Python Homework (Numpy, Pandas)


1. What does Pandas stand for?
* Stands for either:
    Panel Data
    Python Data Analysis


2. What are the 2 collections used in Pandas?
* Series and Dataframes:
In Pandas, a Series is essentially a column, and a DataFrame is a two-dimensional table made up of a collection of Series.

3. Name 4 things Pandas can do for us.
* Pandas can do:
 Data Cleansing	
 Data normalization	
 Data visualization	
 Data inspection	 



4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
* The keyword to use is 'inplace'.


5. What is a CSV?
* A CSV is a comma separated file. 


6. When cleaning data what values do we not like in our data?
* Null values

# Coding Exericises

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

In [37]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array = array1.reshape(2, 3, 2)
print(reshaped_array)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

In [38]:
import numpy as np
array_a = np.linspace(0,20,6)
print(array_a)

[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [39]:
import numpy as np

array_a = np.linspace(0, 20, 6)

array_a_copy = np.copy(array_a)

print(array_a_copy)

[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'..

In [40]:
import numpy as np
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis = 0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray

In [41]:
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

In [43]:
reshape_array = reshaped_array.reshape(4,3)
green, blue, yellow, orange = reshape_array
print(green)
print(blue)
print(yellow)
print(orange)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


13. Combined and sort the following arrays into one called 'comboArray' ...

In [44]:
a = ([10, 11, 12, 13, 14, 15, 16, 17])
b = ([20, 21, 22, 23, 24, 25, 26, 27])
c = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((a, b, c))
print(np.sort(comboArray))

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:

In [46]:
# print sec1 - the 2nd element
print("Sec1:", comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print("Sec2:", comboArray[4:])
# print sec3 - all elements from the 4th to the 14th elements
print("Sec3:", comboArray[5:15])
# print sec4 - the last 6 elements
print("Sec4:", comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print("Sec5:", comboArray[-19:-7])
# print sec6 - from #20 every even element to the end
print("Sec6:", comboArray[20::2])
# print sec7 - from the last element moving forward, every 5th element.
print("Sec7:", comboArray[::-5])

Sec1: 11
Sec2: [14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
Sec3: [15 16 17 20 21 22 23 24 25 26]
Sec4: [2 3 4 5 6 7]
Sec5: [15 16 17 20 21 22 23 24 25 26 27  0]
Sec6: [4 6]
Sec7: [ 7  2 25 20 13]


15. Using Series, create a DataFrame that looks like this:

Ingredients	Quantity	Unit
Flour	4	cups
Milk	1	cup
Eggs	2	large
Spam	1	can

In [47]:
import pandas as pd

In [48]:
Ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
Unit = pd.Series(['Cups', 'Cup', 'Large', 'Can'], name = 'Unit')

Dinner = pd.concat([Ingredients, Quantity, Unit], axis = 1)
print(Dinner)

  Ingredients  Quantity   Unit
0       Flour         4   Cups
1        Milk         1    Cup
2        Eggs         2  Large
3        Spam         1    Can


16. Take this data and create a DataFrame named studentData

In [49]:
import pandas as pd

In [50]:

data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)


      Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc    Dakar   21      Parrot         Cricket


In [51]:
import pandas as pd

In [59]:
import pandas as pd

data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)

desserts = ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
studentData.insert(7, column='Desserts', value=desserts)

print(studentData)



      Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc    Dakar   21      Parrot         Cricket   

       Desserts  
0     Ice Cream  
1  Cashew Fudge  
2       Waffles  
3  Carrot Halwa  


17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [61]:


data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    'Desserts': ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
}

studentData = pd.DataFrame(data)


new_desserts = ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
studentData['Desserts'] = new_desserts

print(studentData)


      Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc    Dakar   21      Parrot         Cricket   

       Desserts  
0     Ice Cream  
1  Cashew Fudge  
2       Waffles  
3  Carrot Halwa  


18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [62]:
import pandas as pd

data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    'Desserts': ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
}

studentData = pd.DataFrame(data)


studentData = studentData.sort_values(by=['Name', 'Address'], ascending=[True, True])

print(studentData)


      Name  Height Qualification  Address  Age        Pets           Sport  \
3     Anuj     5.2           Msc    Dakar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       Waffles  
0     Ice Cream  
1  Cashew Fudge  


19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

In [63]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')


20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

In [64]:
df = pd.DataFrame({'Vegetables': ['Carrots', 'Green Beans', 'Celery', 'Cucumber']})
print(df)
df.to_csv('Vegetables.csv')

    Vegetables
0      Carrots
1  Green Beans
2       Celery
3     Cucumber


20. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [70]:
Flavor = ['Bad', 'Good', 'Great', 'Delicious']
df['Taste'] = Flavor
print('Savory_Veggies', df)
df.to_csv('Savory_Vegetables.csv')

Savory_Veggies     Vegetables      Taste
0      Carrots        Bad
1  Green Beans       Good
2       Celery      Great
3     Cucumber  Delicious
